# PYTHON TRAINING WEEK 2 EXERCISE

Attempt all Questions

# Section A- Numpy

### 1. Import the numpy library

In [2]:
import numpy as np

### 2a. Create a 1D numpy array with the values [1, 2, 3, 4, 5] and assign it to a variable named "a"  
### 2b. Find the shape of the array "a"

In [4]:


a = np.array([1, 2, 3, 4, 5])
print(a.shape)

# a = a.reshape(2, 3)
print(a)


print(a[a > 2])

print(np.mean(a))
print(np.std(a))

(5,)
[1 2 3 4 5]
[3 4 5]
3.0
1.4142135623730951


### 3. Find the minimum and maximum values in the array "a"

In [5]:
print(np.min(a))
print(np.max(a))


1
5


### 4. Create a 2D array

In [6]:
b = np.array([[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
b

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
a

array([1, 2, 3, 4, 5])

### 4b Find the sum and product of "a" & "b"

In [7]:
# sum(a, b)

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
a + b

array([[ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20]])

In [ ]:
a * b

array([[ 6, 14, 24, 36, 50],
       [11, 24, 39, 56, 75]])

In [ ]:
# code here

### 5. Transpose "b"
hint: use transpose method

In [ ]:
b.T

array([[ 6, 11],
       [ 7, 12],
       [ 8, 13],
       [ 9, 14],
       [10, 15]])

### 6a. Sort  'arr' 
### 6b. Reshape  'arr' to  3 by 2 

In [9]:
arr = np.array([45, 75, 55, 34, 21, 6])


In [10]:
arr.reshape((3,2))

array([[45, 75],
       [55, 34],
       [21,  6]])

### 7. Create a numpy array with shape (5, 4) filled with zeros

In [11]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Section B Pandas

### 1. Import pandas library

In [12]:
# code here
import pandas as pd

### 2. Convert the 1D arrays to pandas series

In [13]:
# code here
pd.Series(a)

0    1
1    2
2    3
3    4
4    5
dtype: int32

### 3. Convert the 2D array to pandas dataframe

In [14]:
# code here
pd.DataFrame(b)

0   1   2   3   4
0   6   7   8   9  10
1  11  12  13  14  15

### 5. What is the difference between a pandas series and dataFrame


write text here

# Section C- Data Exploration with Pandas

In [1]:
values = {'points': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
            'X':[78, 85, 96, 80, 86, 100, 55, 80, 45, 30], 
            'Y':[84, 94, 89, 83, 86, 0, 66, 78, 65, 25],
            'Z':[86, 97, 96, 72, 83,  0, 99, 43, 67, 2]}

### Using the values dictionary answer the following question

### 1. Create a new dataframe called df

In [16]:
type(values)

dict

In [2]:
# write code here
import pandas as pd
df = pd.DataFrame(values)
df

points    X   Y   Z
0      a   78  84  86
1      b   85  94  97
2      c   96  89  96
3      d   80  83  72
4      e   86  86  83
5      f  100   0   0
6      g   55  66  99
7      h   80  78  43
8      i   45  65  67
9      j   30  25   2

###  2a. How many row and columns are in df?
### 2b. Print the first 3 rows in df

In [40]:
# write code here
df.shape

(10, 4)

In [41]:
df.shape[0]

10

In [42]:
df.shape[1]

4

In [43]:
df.head(3)

points   X   Y   Z
0      a  78  84  86
1      b  85  94  97
2      c  96  89  96

### 3. Check the number of columns and rows in the dataframe

In [ ]:
# write code here

### 4. Check dataframe info

In [18]:
# write code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   points  10 non-null     object
 1   X       10 non-null     int64 
 2   Y       10 non-null     int64 
 3   Z       10 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 448.0+ bytes


### 5. Describe the dataframe  
Hint: use .describe

In [46]:
# write code here
df.describe()

X          Y          Z
count   10.000000  10.000000  10.000000
mean    73.500000  67.000000  64.500000
std     22.726636  30.728199  37.467764
min     30.000000   0.000000   0.000000
25%     60.750000  65.250000  49.000000
50%     80.000000  80.500000  77.500000
75%     85.750000  85.500000  93.500000
max    100.000000  94.000000  99.000000

### 6. Print the out the columns available

In [47]:
# write code here
df.columns

Index(['points', 'X', 'Y', 'Z'], dtype='object')

### 7. Rename the columns from uppercase to lower case

In [56]:
# write code here
df.columns = [x.lower() for x in df.columns]
df

points    x   y   z
0      a   78  84  86
1      b   85  94  97
2      c   96  89  96
3      d   80  83  72
4      e   86  86  83
5      f  100   0   0
6      g   55  66  99
7      h   80  78  43
8      i   45  65  67
9      j   30  25   2

### 8. What is the data type in the different columns

In [57]:
# write code here
df.dtypes

points    object
X          int64
Y          int64
Z          int64
dtype: object

### 9. What is the min, max and median in the x, y and z columns respectively

In [23]:
# write code here
df.describe()

x          y          z
count   10.000000  10.000000  10.000000
mean    73.500000  67.000000  64.500000
std     22.726636  30.728199  37.467764
min     30.000000   0.000000   0.000000
25%     60.750000  65.250000  49.000000
50%     80.000000  80.500000  77.500000
75%     85.750000  85.500000  93.500000
max    100.000000  94.000000  99.000000

### 10. Make the 'point' column the index of the dataframe 

In [3]:
df

points    X   Y   Z
0      a   78  84  86
1      b   85  94  97
2      c   96  89  96
3      d   80  83  72
4      e   86  86  83
5      f  100   0   0
6      g   55  66  99
7      h   80  78  43
8      i   45  65  67
9      j   30  25   2

In [5]:
df.set_index('points', drop =False)

points    X   Y   Z
points                    
a           a   78  84  86
b           b   85  94  97
c           c   96  89  96
d           d   80  83  72
e           e   86  86  83
f           f  100   0   0
g           g   55  66  99
h           h   80  78  43
i           i   45  65  67
j           j   30  25   2

In [59]:
# write code here
df.index = df['points']
df

points    X   Y   Z
points                    
a           a   78  84  86
b           b   85  94  97
c           c   96  89  96
d           d   80  83  72
e           e   86  86  83
f           f  100   0   0
g           g   55  66  99
h           h   80  78  43
i           i   45  65  67
j           j   30  25   2

### 11. Create a new column called 'sum_xyz' which is a sum of x, y and z columns

In [7]:
# write code here
df['sum_xyz'] = df['X']+ df['Y']+ df['Z']
df

points    X   Y   Z  sum_xyz
0      a   78  84  86      248
1      b   85  94  97      276
2      c   96  89  96      281
3      d   80  83  72      235
4      e   86  86  83      255
5      f  100   0   0      100
6      g   55  66  99      220
7      h   80  78  43      201
8      i   45  65  67      177
9      j   30  25   2       57

In [9]:
df['x_over_y'] = df['X']/ df['Z']
df

points    X   Y   Z  sum_xyz   x_over_y
0      a   78  84  86      248   0.906977
1      b   85  94  97      276   0.876289
2      c   96  89  96      281   1.000000
3      d   80  83  72      235   1.111111
4      e   86  86  83      255   1.036145
5      f  100   0   0      100        inf
6      g   55  66  99      220   0.555556
7      h   80  78  43      201   1.860465
8      i   45  65  67      177   0.671642
9      j   30  25   2       57  15.000000