# Week 2: 
- Arithmetic Operations
- Numpy
- Data, Wrangling/Cleaning, Python Libraries.

## Arithmetic Operations
* addition
* subratction
* division
* Multiplication

In [1]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/_yspSvJoPII?si=L-ZQ438gYFNLS_S6" 
        </iframe>

In [1]:
3 + 5

8

In [2]:
4 * 7

28

In [3]:
9/3


3.0

In [4]:
7-5

2

In [5]:
#whole number
7//5

1

In [6]:
#fraction
7/5

1.4

In [7]:
# Remainder
7%5

2

In [8]:
min([4, 8, 7, 8])

4

In [9]:
max([4, 8, 7, 12])

12

In [10]:
3**2

9

In [11]:
abs(-50)

50

In [12]:
round(65.7)

66

In [13]:
import math
math.ceil(65.5)

66

In [14]:
math.floor(65.7)

65

In [15]:
math.sqrt(49)

7.0

# Python Iterators and Operators

- equals ==  
- not equal !=  
- greater than >  
- less than <  
- greater than or equals >=    
- less tha or equal to <=

These conditions can be used in several ways, most commonly in "if statements" and loops.

if, elif, else

multiple conditions ( and, or)

nested if

In [2]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/FK4vOm037zQ?si=2UIioILFXM1BZovQ" 
        </iframe>

if **condition**:
     do something

In [19]:
x= 400
y= 50

In [20]:
if x > 300:
    print(x)

In [21]:
if x < 400:
    print(x)

In [22]:
if x <= 400:
    print(x)

400


In [23]:
if y != x:
    print(y)

50


In [24]:
if y > 100:
    z= y * x
    print(z)
elif y < 100:
    z = y + x
    print(z)
else:
    print('No condition met')

450


In [25]:
if y > 10 or x < 200:
    print(x * y)

20000


In [26]:
if y > 10 & x < 200:
    print(x * y)

20000


## While Loop

In [3]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/ZdRPvKTlJNQ?si=Jv1lgy7uXmiFkYdZ" 
        </iframe>

In [27]:
i =100 

num = []

while i > 10:
    num.append(i)
    print(num)
    if i == 50:
        break
    i -=10

[100]
[100, 90]
[100, 90, 80]
[100, 90, 80, 70]
[100, 90, 80, 70, 60]
[100, 90, 80, 70, 60, 50]


In [28]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


## List Comprehension

In [4]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/bLmhN4ydw5U?si=3A9fXmea5cgwACdy" 
        </iframe>

In [29]:
code = 'LKJ1234DG56GX9TV'


In [30]:
num = []
for c in code:
    if c.isnumeric():
        num.append(int(c))
        

In [31]:
num

[1, 2, 3, 4, 5, 6, 9]

In [32]:
# list comprehensions
num2 = [int(c) for c in code if c.isnumeric()]

In [33]:
num2

[1, 2, 3, 4, 5, 6, 9]

In [34]:
animals = ['Tiger', 'Bear', 'Elephant', 'Giraffe', 'Zebra', 'Gorilla']

In [35]:
animals_caps = [z for z in animals if len(z) > 5]
animals_caps

['Elephant', 'Giraffe', 'Gorilla']

In [38]:
animals_caps2=[]
for a in animals:
    if len(a) > 5:
        animals_caps2.append(a)
    

In [39]:
animals_caps2

['Elephant', 'Giraffe', 'Gorilla']

# NUMPY

In [5]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/EoqMc-_9V9s?si=K1kQqIEKWq-lyVv_" 
        </iframe>

In [8]:
import numpy as np

## N-dimensional arrays

In [41]:
np.__version__

'1.21.5'

In [9]:
a = np.array([1, 2, 3, 4])

In [43]:
type(a)

numpy.ndarray

In [44]:
a.ndim

1

In [45]:
a.shape

(4,)

In [46]:
a

array([1, 2, 3, 4])

In [10]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
b.shape

(2, 4)

In [49]:
b.ndim

2

In [50]:
c = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13,14, 15, 16]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [51]:
c.ndim

3

In [13]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/Q2RWEAzAtNE?si=hyUAQ7PxovtlwW0B" 
        </iframe>

In [11]:
a + b

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [12]:
a * b

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

In [52]:
a = np.array([1, 2,3, 4])

In [53]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Indexing arrays

In [54]:
b[0, 2]

3

In [55]:
b[1, 1]

6

In [56]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [57]:
c[1,1, -1]

16

## Reshaping Arrays

In [14]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/4Ojoye9YoY0?si=Zsj7AceyVIng1fwe" 
        </iframe>

In [58]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros((3, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [60]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
a.ndim

1

In [62]:
a.reshape((2, 2)).ndim

2

In [63]:
np.arange(4)

array([0, 1, 2, 3])

In [64]:
z = np.arange(2, 10, 2)

In [65]:
z

array([2, 4, 6, 8])

In [66]:
np.random.random((3, 2))

array([[0.18571535, 0.99276823],
       [0.88016491, 0.76040045],
       [0.02735857, 0.2585048 ]])

In [67]:
np.random.seed(5)
np.random.random((3, 2))

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386]])

# Pandas

In [24]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/L19CDhrFEoA?si=DNREjpysXOmR1t3Z" 
        </iframe>

In [25]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/3AK_vockNJg?si=48ZZFbP1rWAbbiY0" 
        </iframe>

In [26]:
import pandas as pd

In [27]:
print(pd.__version__)

2.2.1


In [28]:
a

array([1, 2, 3, 4])

In [29]:
a_ = pd.Series(a)

In [30]:
type(a)

numpy.ndarray

In [31]:
type(a_)

pandas.core.series.Series


## Pandas DataFrame

In [32]:
b 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
b_ = pd.DataFrame(b, columns= ['first', 'second', 'third', 'fourth'])
b_

first  second  third  fourth
0      1       2      3       4
1      5       6      7       8

In [34]:
b[:,1]

array([2, 6])

## Dictionary to Pandas DataFrame

In [35]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/bSYTY4URrQI?si=X6LqwXZoQmuET_sM" 
        </iframe>

In [36]:
data = {'name': ['John', 'Jane', 'Bob', 'Sara', 'Tom', 'James', 'Philip', None, 'White', 'Susan', 'Becky', 'Brown', 'Matt', 'Ore'],
        'age': [32, 27, 45, None, 38, '55', 23, 43, 32, 50, None, 22, 33, 47],
        'gender': ['M', 'f', 'M', 'F', 'm', None, 'M', 'F', 'M', 'F', 'f', 'M', 'N/A', 'None'],
        'income (£)': [50000, 60000, None, 72000, None, 80000, 32000, '55000', 43000, 85000, 60000, 450000, 56.000, 7000],
        'occupation': ['Doctor', 'Scientist', 'Technician', None, 'Banker', 'Beautician', 'Artist', 'Entrepreneur', 'Nurse', 'Data Analyst', 'Engineer', 'Teacher', 'Nurse', 'Trader'],
        'address': ['Cape town', 'London',  'New York', 'Tokyo', None, 'Chicago', 'Houston',  'Texas', 'Manchester', 'Paris', 'Berlin', 'Dubai', 'Madrid', 'Lagos']}

In [37]:
df = pd.DataFrame(data)
df

name   age gender income (£)    occupation     address
0     John    32      M      50000        Doctor   Cape town
1     Jane    27      f      60000     Scientist      London
2      Bob    45      M       None    Technician    New York
3     Sara  None      F      72000          None       Tokyo
4      Tom    38      m       None        Banker        None
5    James    55   None      80000    Beautician     Chicago
6   Philip    23      M      32000        Artist     Houston
7     None    43      F      55000  Entrepreneur       Texas
8    White    32      M      43000         Nurse  Manchester
9    Susan    50      F      85000  Data Analyst       Paris
10   Becky  None      f      60000      Engineer      Berlin
11   Brown    22      M     450000       Teacher       Dubai
12    Matt    33    N/A       56.0         Nurse      Madrid
13     Ore    47   None       7000        Trader       Lagos

In [38]:
df.head(2)

name age gender income (£) occupation    address
0  John  32      M      50000     Doctor  Cape town
1  Jane  27      f      60000  Scientist     London

In [39]:
df.tail(3)

name age gender income (£) occupation address
11  Brown  22      M     450000    Teacher   Dubai
12   Matt  33    N/A       56.0      Nurse  Madrid
13    Ore  47   None       7000     Trader   Lagos

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        13 non-null     object
 1   age         12 non-null     object
 2   gender      13 non-null     object
 3   income (£)  12 non-null     object
 4   occupation  13 non-null     object
 5   address     13 non-null     object
dtypes: object(6)
memory usage: 804.0+ bytes


In [41]:
df.describe()

name  age gender  income (£) occupation    address
count     13   12     13          12         13         13
unique    13   11      6          11         12         13
top     John   32      M       60000      Nurse  Cape town
freq       1    2      5           2          2          1

In [42]:
df.shape

(14, 6)

In [43]:
df.columns

Index(['name', 'age', 'gender', 'income (£)', 'occupation', 'address'], dtype='object')

In [44]:
df.values

array([['John', 32, 'M', 50000, 'Doctor', 'Cape town'],
       ['Jane', 27, 'f', 60000, 'Scientist', 'London'],
       ['Bob', 45, 'M', None, 'Technician', 'New York'],
       ['Sara', None, 'F', 72000, None, 'Tokyo'],
       ['Tom', 38, 'm', None, 'Banker', None],
       ['James', '55', None, 80000, 'Beautician', 'Chicago'],
       ['Philip', 23, 'M', 32000, 'Artist', 'Houston'],
       [None, 43, 'F', '55000', 'Entrepreneur', 'Texas'],
       ['White', 32, 'M', 43000, 'Nurse', 'Manchester'],
       ['Susan', 50, 'F', 85000, 'Data Analyst', 'Paris'],
       ['Becky', None, 'f', 60000, 'Engineer', 'Berlin'],
       ['Brown', 22, 'M', 450000, 'Teacher', 'Dubai'],
       ['Matt', 33, 'N/A', 56.0, 'Nurse', 'Madrid'],
       ['Ore', 47, 'None', 7000, 'Trader', 'Lagos']], dtype=object)

In [45]:
df['name'].unique()

array(['John', 'Jane', 'Bob', 'Sara', 'Tom', 'James', 'Philip', None,
       'White', 'Susan', 'Becky', 'Brown', 'Matt', 'Ore'], dtype=object)

In [46]:
df['name'].nunique()

13

In [47]:
df.age

0       32
1       27
2       45
3     None
4       38
5       55
6       23
7       43
8       32
9       50
10    None
11      22
12      33
13      47
Name: age, dtype: object

# Data Transformation

In [48]:
%%HTML
<iframe width="560" height="315" 
        src="https://www.youtube-nocookie.com/embed/PgobQzcmxHI?si=qSNUuvJlJDsp5YC9" 
        </iframe>

In [49]:
df['age'].dtype

dtype('O')

In [50]:
df['age'].isna().sum()

2

In [51]:
df['age']=df['age'].fillna(0)

In [52]:
df['age']= df['age'].astype(int)

In [53]:
df['age'].dtype

dtype('int32')

In [54]:
df.isna().sum()

name          1
age           0
gender        1
income (£)    2
occupation    1
address       1
dtype: int64

In [55]:
df['age']

0     32
1     27
2     45
3      0
4     38
5     55
6     23
7     43
8     32
9     50
10     0
11    22
12    33
13    47
Name: age, dtype: int32

In [56]:
df['income (£)'].dtype

dtype('O')

In [57]:
df['income (£)']= df['income (£)'].astype(float)

In [58]:
df.describe()

age     income (£)
count  14.000000      12.000000
mean   31.928571   82838.000000
std    16.776652  118555.852663
min     0.000000      56.000000
25%    24.000000   40250.000000
50%    32.500000   57500.000000
75%    44.500000   74000.000000
max    55.000000  450000.000000

In [59]:
df['age'].isna().sum()

0

In [60]:
df['gender'].isna().sum()

1

In [61]:
df['gender'].nunique()

6

In [62]:
df['gender'].unique()

array(['M', 'f', 'F', 'm', None, 'N/A', 'None'], dtype=object)

In [63]:
df

name  age gender  income (£)    occupation     address
0     John   32      M     50000.0        Doctor   Cape town
1     Jane   27      f     60000.0     Scientist      London
2      Bob   45      M         NaN    Technician    New York
3     Sara    0      F     72000.0          None       Tokyo
4      Tom   38      m         NaN        Banker        None
5    James   55   None     80000.0    Beautician     Chicago
6   Philip   23      M     32000.0        Artist     Houston
7     None   43      F     55000.0  Entrepreneur       Texas
8    White   32      M     43000.0         Nurse  Manchester
9    Susan   50      F     85000.0  Data Analyst       Paris
10   Becky    0      f     60000.0      Engineer      Berlin
11   Brown   22      M    450000.0       Teacher       Dubai
12    Matt   33    N/A        56.0         Nurse      Madrid
13     Ore   47   None      7000.0        Trader       Lagos

In [64]:
df['gender'] = df['gender'].replace({'f': 'F', 'm': 'M', 'N/A': np.nan, 'None': np.nan, None: np.nan})

In [65]:
df['gender'].unique()

array(['M', 'F', nan], dtype=object)

In [66]:
df['gender'].isna().sum()

3